capitolo 3  le variabili
Open-Education-Polito/oep-python-interactive-book pull request #1
Opened 2018-01-25 10:23 UTC by ceolonimatteo

Bisognerebbe solamente piu colorare delle scritte

2018-01-25 11:00 UTC, libremente requested changes
@ceolonimatteo Apporta le modifiche e poi ne parliamo insieme

2018-01-25 11:00 UTC, libremente commented on capitoli/le_variabili.rst
> +.."todo: mettere istruzioni di assegnazione in rosso e scatola1=7 in rosso"
commento errato, vedi sintassi

2018-01-25 11:00 UTC, libremente commented on capitoli/le_variabili.rst
> +e’ quello di scrivere una frase come la seguente, che è chiamata **“istruzione di assegnazione”:**
Usa un altro tipo di blocco, qualcosa di più visibile, così non è chiaro.

2018-01-25 11:06 UTC, libremente requested changes
@ceolonimatteo Rivedi la sintassi perchè ci sono diversi errori. Dopodichè fai sempre un controllo visuale del compilato perchè ci sono errori visibili che non hai corretto. Grazie

2018-01-25 11:06 UTC, libremente commented on capitoli/le_variabili.rst
> +   SCATOLA1 = 7
Qui non è il caso di usare activecode in quanto non c'è niente in output. Usa un altro blocco

2018-01-25 11:06 UTC, libremente commented on capitoli/le_variabili.rst
> +    • -scrivi in Python questa istruzione per il calcolatore:
Perchè * e - insieme?

2018-01-25 11:06 UTC, libremente commented on capitoli/le_variabili.rst
> +FACCIAMO UNA BREVE INTERRUZIONE.
Usa un heading differente per differenziare il font

2018-01-25 11:06 UTC, libremente commented on capitoli/le_variabili.rst
> +1.Il mago Silvan fa tanti giochi di magia: dal suo cappello a cilindro escono tre conigli bianchi e due neri. Quanti conigli sono nascosti nel cappello?
Penso che questo elenco sia errato, rivedi la sintassi

2018-01-25 11:06 UTC, libremente commented on capitoli/le_variabili.rst
> +VALUTAZIONE: 1 PUNTO CIASCUNO PER I PRIMI CINQUE ESERCIZI,
Anche qui, usa degli heading differenti.

2018-01-25 11:06 UTC, libremente commented on capitoli/le_variabili.rst
> +
Perchè ci sono tutti questi \n?

2018-01-25 11:06 UTC, libremente commented on capitoli/le_variabili.rst
> +6.*(difficilissimo, se riesci a farlo sei --- un mago!)*
Errato uso di *, attenzione agli spazi.

2018-01-25 11:06 UTC, libremente commented on capitoli/le_variabili.rst
> +Se scriviamo **print(SCATOLA1)** il calcolatore:
Elenco errato, rivedi sintassi

2018-01-25 11:27 UTC, libremente commented
@ceolonimatteo rinomina il file in `Terzo_Passo_Variabili.rst`
Grazie

2018-01-29 08:11 UTC, libremente requested changes
Ho rivisto i cambiamenti, continuano ad esserci problemi con i blocchi RST. Attenzione agli spazi richiesti perché in molti casi è necessario mettere una linea vuota tra un blocco ed il successivo perché questo sia correttamente applicato. Riguarda le righe che ti ho commentato e vedrai che ci sono degli errori. Anche se nell'editor vedi il ritorno a capo, questo non sempre basta per andare a capo anche nell'html. Rivedi la sintassi. Grazie.

2018-01-29 08:11 UTC, libremente commented on capitoli/Terzo_Passo_Le_Variabili.rst
> +**SCATOLA1=7**
Inserire una nuova linea qui sennò non si legge

2018-01-29 08:11 UTC, libremente commented on capitoli/Terzo_Passo_Le_Variabili.rst
> +   SCATOLA2 = 3.14
Andare a capo tra una e l'altra

2018-01-29 08:11 UTC, libremente commented on capitoli/Terzo_Passo_Le_Variabili.rst
> +SCATOLA3 = "come va?"
Manca un a capo prima di linea 24 perchè sennò è tutto sulla stessa riga

2018-01-29 08:11 UTC, libremente commented on capitoli/Terzo_Passo_Le_Variabili.rst
> +*DOMANDA*
Vai a capo dopo DOMANDA

2018-01-29 08:11 UTC, libremente commented on capitoli/Terzo_Passo_Le_Variabili.rst
> +• cerca la scatola indicata (in questo caso SCATOLA1)
metti a posto questo elenco. Se guardi nel browser non è un elenco. Devi porre più attenzione agli spazi/righe vuote che caratterizzano il formato rst

2018-01-29 08:11 UTC, libremente commented on capitoli/Terzo_Passo_Le_Variabili.rst
> +     -scrivi in Python questa istruzione per il calcolatore:
Secondo me il formato "-parola" non è molto bello. Metterei un elenco puntato

2018-01-29 08:11 UTC, libremente commented on capitoli/Terzo_Passo_Le_Variabili.rst
> +VOGLIAMO RACCONTARTI LA STORIA DI PYTHON.
Metti un a capo dopo questa linea.

2018-01-29 08:11 UTC, libremente commented on capitoli/Terzo_Passo_Le_Variabili.rst
> +-1)Il mago Silvan fa tanti giochi di magia: dal suo cappello a cilindro escono tre conigli bianchi e due neri. Quanti conigli sono nascosti nel cappello?
Anche qui rivedi l'elenco, non mi sembra che sia renderizzato correttamente.

2018-01-29 09:54 UTC, libremente requested changes
Cambiamenti richiesti.

2018-01-29 09:54 UTC, libremente commented on capitoli/Terzo_Passo_Variabili.rst
>  VALUTAZIONE: 1 PUNTO CIASCUNO PER I PRIMI CINQUE ESERCIZI,
Toglierei questa parte di valutazione.

2018-01-29 09:54 UTC, libremente commented on capitoli/Terzo_Passo_Variabili.rst
> +Nella classe 3D della scuola ci sono 8 maschi e 10 femmine. Se Mario è alto m. 1.55, Fabio,
Perchè questo blocco non è indentato correttamente? Io lo vedo fuori dal blocco puntato

2018-01-29 09:54 UTC, libremente commented on capitoli/Terzo_Passo_Variabili.rst
> +Il suo inventore è un geniale signore olandese: :boltred:`Guido Van Rossum`
Manca il punto a fine riga (qui e in altri posti lo stesso). Ricontrolla bene

2018-01-29 09:54 UTC, libremente commented on capitoli/Terzo_Passo_Variabili.rst
>  Il modo più semplice per farsi consegnare una scatola dal calcolatore,darle un nome e riempirla con un numero
Sempre lo spazio dopo la virgola

2018-01-29 09:54 UTC, libremente commented on capitoli/Terzo_Passo_Variabili.rst
>  *DOMANDA*
Non è chiaro lo spazio, non si capisce.
Metterei un'altra riga vuota sopra e poi il testo più grosso oppure in grassetto

2018-01-29 09:54 UTC, libremente commented on capitoli/Terzo_Passo_Variabili.rst
>  |	**FACCIAMO UNA BREVE INTERRUZIONE.**
Perchè è così indentato?
Se vuoi fare un'interruzione, inserisci una riga verticale (come se fosse un `<hr>` in html).
Si fa con:
`-----------`
e il risultato è:
------------

2018-01-29 09:54 UTC, libremente commented on capitoli/Terzo_Passo_Variabili.rst
> +     - scrivi in Python questa istruzione per il calcolatore:
Perchè c'è la riga verticale a sinistra? Direi di fare un elenco puntato esattamente come sopra.

2018-01-29 09:59 UTC, ceolonimatteo commented on capitoli/Terzo_Passo_Variabili.rst
> +Nella classe 3D della scuola ci sono 8 maschi e 10 femmine. Se Mario è alto m. 1.55, Fabio,
Perche se lo mettevo sotto il testo mi dava errore

2018-01-29 10:29 UTC, libremente requested changes
la review di prima non è stata correttamente implementata. Rivedere

2018-01-29 10:29 UTC, libremente commented on capitoli/Terzo_Passo_Variabili.rst
>  :boltred:`SCATOLA1=7`
qui bisogna andare a capo però sennò non si capisce. Prova a leggere il testo, non è chiaro. Andrei a capo e metterei un blocco dedicato per evidenziare visto che è la prima istruzione di assegnazione che si vede.

2018-01-29 10:29 UTC, libremente commented on capitoli/Terzo_Passo_Variabili.rst
>  *DOMANDA*
Ancora qui lo stesso problema, non va bene lo spazio, non si capisce che c'è una domanda

2018-01-29 10:29 UTC, libremente commented on capitoli/Terzo_Passo_Variabili.rst
> +**FACCIAMO UNA BREVE INTERRUZIONE.**
No, così hai fatto un nuovo titolo. Quello che devi fare è inserire una riga orizzontale PRIMA di questo titoletto e poi usare un heading diverso, cerca nella guida

2018-01-29 10:29 UTC, libremente commented on capitoli/Terzo_Passo_Variabili.rst
> +:boltred:`TOTALE PUNTI`…………………..
Elimina questo

2018-01-29 10:29 UTC, libremente commented on capitoli/Terzo_Passo_Variabili.rst
>  Se Marta, Giovanna, Elisabetta e Francesca sono alte come Mario, mentre Stefania, Chiara e Simonetta sono alte m. 1.50, Daria e Domitilla sono 5
Rimane il problema di prima, tutto questo testo deve essere indentato correttamente come gli esercizi precedenti.

2018-01-29 10:32 UTC, libremente commented on capitoli/Terzo_Passo_Variabili.rst
> +Nella classe 3D della scuola ci sono 8 maschi e 10 femmine. Se Mario è alto m. 1.55, Fabio,
Quale errore? Come è possibile? Se è un blocco di testo che fa parte di un elenco puntato deve restare nella stessa forma/indentazione

2018-01-29 11:53 UTC, libremente approved these changes
👍

2018-01-30 08:26 UTC, merged