Added chapter "Le Funzioni"
Open-Education-Polito/oep-python-interactive-book pull request #7
Opened 2018-01-29 08:19 UTC by Styddy

# Descrizione
Aggiunto capitolo "Le funzioni" con relative immagini.

# Cambiamenti

# Review
- [ ] @libremente

2018-01-29 08:34 UTC, libremente commented
@Styddy se fai uno squash dei 5 commit mi faciliti il lavoro di review, grazie!

2018-01-29 09:39 UTC, libremente requested changes
Apporta le modifiche richieste e poi ne parliamo insieme, grazie.

2018-01-29 09:39 UTC, libremente commented on capitoli/Settimo_Passo_Funzioni.rst
> +|	Questo meccanismo è la :boltred:`“funzione”`
Non mi piace molto questa indentazione. Usa magari un altro heading.

2018-01-29 09:39 UTC, libremente commented on capitoli/Settimo_Passo_Funzioni.rst
> +| :boltblue:`DEFINIZIONE DI FUNZIONE`
Anche questo non mi piace molto, prova con un altro blocco.

2018-01-29 09:39 UTC, libremente commented on capitoli/Settimo_Passo_Funzioni.rst
> +	print ("la risposta esatta è: Manzoni")
errore di indentazione

2018-01-29 09:39 UTC, libremente commented on capitoli/Settimo_Passo_Funzioni.rst
> +	risposta1 = input ("chi e' l'autore dei Promessi Sposi? ")
questo codice non lo vedo colorato, perchè?

2018-01-29 09:39 UTC, libremente commented on capitoli/Settimo_Passo_Funzioni.rst
> +| :boltblue:`Ancora funzioni...ma un po’ più difficili: l’istruzione return`
Non mi piace molto questo paragrafo, prova ad usare un altro heading

2018-01-29 09:39 UTC, libremente commented on capitoli/Settimo_Passo_Funzioni.rst
> +:boltblue:`#programma principale`
mi sembra ci sia un problema qui di spazi, si vede `#`

2018-01-29 09:39 UTC, libremente commented on capitoli/Settimo_Passo_Funzioni.rst
> +|	Ecco il suo racconto.
Non mi piace molto questo paragrafo, prova a cambiare blocco.

2018-01-29 09:39 UTC, libremente commented on capitoli/Settimo_Passo_Funzioni.rst
> +(da: http://it.wikipedia.org)
magari metti il link corretto a GNU, grazie

2018-01-29 10:29 UTC, Styddy commented on capitoli/Settimo_Passo_Funzioni.rst
> +	risposta1 = input ("chi e' l'autore dei Promessi Sposi? ")
Qual è il testo da colorare? Nel libro lo vedo nero

2018-01-29 10:33 UTC, libremente commented on capitoli/Settimo_Passo_Funzioni.rst
> +	risposta1 = input ("chi e' l'autore dei Promessi Sposi? ")
Il codice sorgente deve essere "colorato" automaticamente se il blocco è corretto, infatti sotto va bene, prova a vedere se la sintassi per il codice è corretta.

2018-01-29 10:38 UTC, Styddy commented on capitoli/Settimo_Passo_Funzioni.rst
> +	risposta1 = input ("chi e' l'autore dei Promessi Sposi? ")
Errore trovato, c'era una riga che andava a capo.

2018-01-29 10:48 UTC, Styddy commented on capitoli/Settimo_Passo_Funzioni.rst
> +:boltblue:`#programma principale`
Nel libro c'è proprio il carattere #, è voluto che si veda.

2018-01-29 10:50 UTC, libremente commented on capitoli/Settimo_Passo_Funzioni.rst
> +:boltblue:`#programma principale`
Ok, allora rimuoviamolo comunque. Trattalo come "con" e "senza" messi sopra.

2018-01-29 11:11 UTC, libremente requested changes
Direi che va bene, aggiusta solo un paio di cose, grazie

2018-01-29 11:11 UTC, libremente commented on capitoli/Settimo_Passo_Funzioni.rst
> +Questo meccanismo è la :boltred:`“funzione”`
Metti i punti finali

2018-01-29 11:11 UTC, libremente commented on capitoli/Settimo_Passo_Funzioni.rst
> +(da: http://it.wikipedia.org/wiki/linux)
Ok aggiungi anche https://it.wikipedia.org/wiki/GNU

2018-01-29 11:11 UTC, libremente commented on capitoli/Settimo_Passo_Funzioni.rst
> +Ecco il suo racconto.
Metti le 4 libertà come elenco numerato partendo da `0`

2018-01-29 11:11 UTC, libremente commented on capitoli/Settimo_Passo_Funzioni.rst
> +-----------------------------------
Se vogliamo usarlo come titolo allora può andar bene ma metti solo la prima lettera in maiuscolo.

2018-01-29 11:19 UTC, libremente commented on capitoli/Settimo_Passo_Funzioni.rst
> +	risposta1 = input ("chi e' l'autore dei Promessi Sposi? ")
👍

2018-01-30 08:43 UTC, libremente commented
Ottimo! Fai uno squash e un rebase e poi facciamo il merge, grazie! 👍

2018-01-30 08:52 UTC, libremente approved these changes

2018-01-30 08:52 UTC, merged

2018-01-30 08:52 UTC, libremente commented
Ottimo lavoro, grazie! 👍